package com.clouway.jobex.server.job.jobannounce;

import com.clouway.jobex.server.job.Job;
import com.clouway.jobex.server.job.JobRepository;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mock;

import static org.hamcrest.Matchers.is;
import static org.hamcrest.Matchers.notNullValue;
import static org.junit.Assert.assertThat;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import static org.mockito.MockitoAnnotations.initMocks;

/**
 * @author Ivan Lazov <darkpain1989@gmail.com>
 */
public class JobAnnounceServiceImplTest {

  private JobAnnounceService service;

  @Mock
  private JobRepository repository;

  @Before
  public void setUp() {
    initMocks(this);
    service = new JobAnnounceServiceImpl(repository);
  }

  @Test
  public void prepareNewJobWithAutoGeneratedId() {

    when(repository.prepareNewJob()).thenReturn(new Job());

    Job job = service.prepareNewJob();

    verify(repository).prepareNewJob();

    assertThat(job, is(notNullValue()));
  }

  @Test
  public void announceJobWithGivenCompany() {

    String companyName = "myCompany";
    Job job = new Job();

    service.announceJob(companyName, job);

    verify(repository).saveJob(companyName, job);
  }
}
